filegroup(
    name = "input_data",
    srcs = ["input.xml"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "output_data",
    srcs = ["output.csv"],
    visibility = ["//visibility:public"],
)
