filegroup(
    name = "input_data",
    srcs = [
        "frequencies.csv",
        "input.xml",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "output_data",
    srcs = [
        "output-vocab.csv",
        "output-listening.csv",
    ],
    visibility = ["//visibility:public"],
)
